/**
 * Created by bear on 2017/12/26.
 */
export const messageTypes = {
    MSG_REQUEST_LIST: 'MSG_REQUEST_LIST',
    MSG_RECEIVE_LIST: 'MSG_RECEIVE_LIST'
}

export const authTypes = {
    USER_LOGIN: 'USER_LOGIN',
    USER_REG: 'USER_REG',
    USER_MODIFY: 'USER_MODIFY',
    USER_PROFILE: 'USER_PROFILE',
    USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
}

export const contactTypes = {
    REQUEST_CST_LIST: 'REQUEST_CST_LIST',
    RECEIVE_CST_LIST: 'RECEIVE_CST_LIST',
    RECORD_SECTION: 'RECORD_SECTION'

}
export const applicationTypes = {
    REQUEST_GRID_LIST: 'REQUEST_GRID_LIST',
    RECEIVE_GRID_LIST: 'RECEIVE_GRID_LIST',

}
export const socketTypes = {
    SOCKET_CONNECTION: 'SOCKET_CONNECTION',
    SOCKET_CONNECTION_FAIL: 'SOCKET_CONNECTION_FAIL',
    SOCKET_DISCONNECTION: 'SOCKET_DISCONNECTION',
    SOCKET_EMIT_MESSAGE:'SOCKET_EMIT_MESSAGE',
    SOCKET_ON_MESSAGE:'SOCKET_ON_MESSAGE'

}