/**
 * Created by bear on 2017/12/26.
 */
export const messageTypes = {
  MSG_REQUEST_LIST: 'MSG_REQUEST_LIST',
  MSG_RECEIVE_LIST: 'MSG_RECEIVE_LIST'
};

export const authTypes = {
  USER_LOGIN: 'USER_LOGIN',
  USER_REG: 'USER_REG',
  USER_MODIFY: 'USER_MODIFY',
  USER_PROFILE: 'USER_PROFILE',
  USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD'
};

export const contactTypes = {
  REQUEST_CST_LIST: 'REQUEST_CST_LIST',
  RECEIVE_CST_LIST: 'RECEIVE_CST_LIST',
  RECORD_SECTION: 'RECORD_SECTION'
};
export const applicationTypes = {
  REQUEST_GRID_LIST: 'REQUEST_GRID_LIST',
  RECEIVE_GRID_LIST: 'RECEIVE_GRID_LIST'
};
export const socketTypes = {
  SOCKET_CONNECTION: 'SOCKET_CONNECTION',
  SOCKET_CONNECTION_FAIL: 'SOCKET_CONNECTION_FAIL',
  SOCKET_DISCONNECTION: 'SOCKET_DISCONNECTION',
  SOCKET_EMIT_MESSAGE: 'SOCKET_EMIT_MESSAGE',
  SOCKET_ON_MESSAGE: 'SOCKET_ON_MESSAGE',
  SOCKET_SAVE_CURRENT_CHAT_KEY: 'SOCKET_SAVE_CURRENT_CHAT_KEY',
  SOCKET_DEL_CURRENT_CHAT_KEY: 'SOCKET_DEL_CURRENT_CHAT_KEY',
  SOCKET_CURRENT_HISTORY: 'SOCKET_CURRENT_HISTORY',
  SESSION_SAVE_TO_LOCAL: 'SESSION_SAVE_TO_LOCAL',
  SESSION_RESTORE: 'SESSION_RESTORE'
};
export const dynamicTypes = {
  REQUEST_TOPICS_LIST: 'REQUEST_TOPICS_LIST',
  RECEIVE_TOPICS_LIST: 'RECEIVE_TOPICS_LIST',
  GET_ARTICLE_DETAIL: 'GET_ARTICLE_DETAIL'
};
